### ISSUE TITLE
Jackson serialization of Page misses type information due to being a simpleType [DATACMNS-1099]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1542]
**[Mark Czubin](https://jira.spring.io/secure/ViewProfile.jspa?name=czubin@gmail.com)** opened **[DATACMNS-1099](https://jira.spring.io/browse/DATACMNS-1099?redirect=false)** and commented

When serializing a list\<T>, spring will provide Jackson the parametrized type T of the list
, if and only if, the type is a collection-like type.
This is needed when using polymorphism (`@JsonTypeInfo` etc).

E.g. ```
List\<Animals> = List.of(Dog, Cat);

```
Should yield ```
[{
 "@type" = "dog",
  ...
}, {
 "@type" = "cat",
  ...
}] 
```

I've added support for this in my own application with a Jackson Module. Though it could be extended to chunks and slices.

```java
public class PageJacksonConfiguration implements SpringDataJacksonModules {
	@Bean
	public PageModule jacksonPageModule() {
		return new PageModule();
	}
}

public class PageModule extends SimpleModule {

    private static final long serialVersionUID = -4383075238418447967L;

    public PageModule() {
        super(PageModule.class.getName(), new Version(1, 0, 0, null, null, null));
    }

    @Override
    public void setupModule(SetupContext context) {
        super.setupModule(context);
        context.addTypeModifier(new PageModifier());
    }

    static class PageModifier extends TypeModifier {
        @Override
        public JavaType modifyType(JavaType type, Type jdkType,
                                   TypeBindings bindings,
                                   TypeFactory typeFactory) {

            if (type.isReferenceType() || type.isContainerType()) {
                return type;
            }

            Class<?> raw = type.getRawClass();
            if (Page.class.isAssignableFrom(raw)) {

                final JavaType[] params = typeFactory.findTypeParameters(type, Page.class);

                if (params == null || params.length == 0) {
                    return typeFactory.constructReferenceType(raw, TypeFactory.unknownType());
                }

                return typeFactory.constructCollectionLikeType(raw, params[0]);
            }
            return type;
        }
    }
}
```

---
No further details from [DATACMNS-1099](https://jira.spring.io/browse/DATACMNS-1099?redirect=false)

**Comment by mp911de** [comment]
We never intended `Page` to be JSON-serializable as we would provide a contract that was never intended to be there in the first place. Our own support to render pages uses Spring HATEOAS' `PagedModel` to transform it into various representations and that is our recommended approach.

**Comment by ghferrari** [comment]
I've just hit this same issue and wanted to add my 2c...

The one and only raison d'être of `org.springframework.data.web.PagedModel` is to provide a stable representation (including JSON serializations) of a `Page` of data which reflects the fact that `PageImpl` is an internal domain entity whose API might change - cf https://docs.spring.io/spring-data/relational/reference/repositories/core-extensions.html#core.web.page.

The OP's request here is not that `PageImpl` should have a fixed API, but rather that Spring Data should ship with Jackson customisations which allow `PagedModel` to serialize correctly i.e. `PagedModel<T>` should serialize similarly in relevant respects to `List<T>`, which it currently does not.

I imagine this would require the Spring Data team to take on the commitment of providing and maintaining the relevant Jackson serialization configuration for `PagedModel`, such that, if the underlying `PageImpl` changes, they will update the Jackson serialization for `PagedModel` to take account of those changes, thus keeping the serialization the same even if `PageImpl` has changed. Without that, `org.springframework.data.web.PagedModel` is of much more limited usefulness than the `PagedModel` provided by Spring HATEOAS and (as the OP and I have found out) in some cases appears to produce behaviour that is entirely unexpected.

I think if there's a good enough reason to provide the cutdown `PagedModel` class at all, then there's a good enough reason to make sure it serializes correctly. Otherwise, we should all just be using the Spring HATEOAS `PagedModel`.
