### ISSUE TITLE
Allow instantiation using builders [DATACMNS-1397]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-commons#1832]
**[Jan Rieke](https://jira.spring.io/secure/ViewProfile.jspa?name=jan%20rieke)** opened **[DATACMNS-1397](https://jira.spring.io/browse/DATACMNS-1397?redirect=false)** and commented

With [DATACMNS-1322](https://jira.spring.io/browse/DATACMNS-1322), Spring Data took a step forward towards better support for immutable objects using withers. However, if you have to set a larger number of fields, using withers has the drawback that you create a new instance on every wither call.

Of course you could use "the traditional way" for instantiating immutable objects: a constructor with all fields as parameters. Lombok's `@AllArgsConstructor` is typically used to avoid writing those boilerplate constructors.
However, in our case, we have a class hierarchy for our model classes. It is typically 1 to 3 classes deep, and every superclass has its own properties. Because Lombok's `@AllArgsConstructor` does not include the fields from superclasses (and probably will not in the foreseeable future), we have to manually implement an all-args constructor for every model class. This approach is quite error-prone, because when new fields are added to a superclass, you have to manually alter the constructors of all subclasses.

Recently, Lombok added the [@SuperBuilder feature](https://projectlombok.org/features/experimental/SuperBuilder), which significantly improves the applicability of builders in such a case, because a `@SuperBuilder` includes setters for fields from superclasses. It would be extremely useful if we could advise Spring Data to use such a builder when creating instances. Then we could completely remove the (manual) all-args constructors.

Jackson, for instance, takes such an approach; you can use the annotations `@JsonDeserialize` and `@JsonPOJOBuilder` to tell Jackson to use the builder to construct the instance

---
No further details from [DATACMNS-1397](https://jira.spring.io/browse/DATACMNS-1397?redirect=false)

**Comment by JohannesPertl** [comment]
This is a huge issue, yet doesn't seem to get much attention. Any updates?

**Comment by odrotbohm** [comment]
Can you elaborate why you think it's a huge issue? Builders are primarily a developer convenience, both to at writing and reading time. Spring Data object instantiation is none of that. There already is an `EntityInstantiator` API that allows customizing the construction based on the persistence constructor's parameters. Also, there's `CustomConversions`, which – through its store-specific extensions – allows registering Spring `Converter` instances that would even allow you to take care of the entire object instance creation and population explicitly.

**Comment by JohannesPertl** [comment]
As the original poster described: Basically `@AllArgsConstructor`, a fundamental functionality of Lombok, needs [`@SuperBuilder`](https://projectlombok.org/features/experimental/SuperBuilder) to also work with super classes.

**Comment by odrotbohm** [comment]
How far developers mitigate challenges with their object model using Lombok doesn't really play into design decisions in Spring Data.

I was actually referring to the implied severity of the report. "Huge issue" implies that either many users are affected or there's a fundamental problem with no suitable workarounds available. I don't see either of the two. Which means we are essentially back to a discussion about whether the available means to deal with this challenge are enough, and, if not, what additional complexity in the object mapping would be justified to solve an issue that doesn't seem that pressing. The ticket hasn't seen any significant feedback for four years.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by janrieke** [comment]
Sorry for the late feedback, I lost track of this issue due to the GitHub migration.

It's true that you can implement this feature yourself if you need it. However, this has a significant drawback: You have to actually implement it yourself. :wink:

I won't go so far to say that this is an essential feature for a framework like Spring Data, especially given that there is a way to mitigate the issue. However, considering that several other frameworks that do deserialization/instantiation have built-in support for such a feature, I'd vote to make this a Spring Data framework feature to immediately allow _all_ users to benefit from it (i.e., all connector projects like elasticsearch, jpa, redis would get the feature automatically). This would further promote immutable persistent entities, which have many advantages (e.g. reducing bug probability with parallel and functional programming).

We implemented a solution in our own Spring Data project (for our CMS). It was not too complex, but also not trivial, as it involves a lot of reflective code. We use a new annotation that marks classes for builder instantiation (and that also allows some customization like setting the builder method name). Instantiation for classes with this annotation is delegated to our `BuilderBasedEntityInstantiator`.

If this is something you'd consider a valuable addition for all Spring Data projects, I can create a PR for this.
