### ISSUE TITLE
Reactive transaction manager 

### ISSUE THREAD

**Issue by AndreiKoliadenko** [spring-projects/spring-data-commons#2323]
Hello,

It was mentioned at the issue #2286 that ChainedTransactionManager is now deprecated and there are no future plans to implement a reactive analog of it.
Is there any existing alternative for a distributed database reactive transaction?

Example - insert data into both MongoDB and Neo4j in a single reactive transaction.

**Comment by mp911de** [comment]
We decided to deprecate `ChainedTransactionManager` because we cannot reliably ensure consistently committed transactions. We do not plan to implement a pattern that is deprecated in the first place. Probably the best what you can do is register a reactive `TransactionSynchronization` and either apply your logic in `beforeCommit(…)` or `afterCommit(…)` where the Neo4j transaction manager drives the actual transaction.
