### ISSUE TITLE
Breaking change in Spring Boot 2.5.0-M1..M3 related to spring-data-common

### ISSUE THREAD

**Issue by khmarbaise** [spring-projects/spring-data-commons#2331]
Based on the upgrade to Spring Boot 2.5.0-M2 and 2.5.0-M3 we are testing (upgrading from 2.4.3) we realized there is a breaking change in an interface `org.springframework.data.domain.Pageable` which is in `spring-data-common` (picked up by this upgrade). The problem is based on adding a new method `withPage(..)` without adding a default implementation (I can't say if it would be a good idea to do so or not.).

We got the error message:
```
XXX is not abstract and does not override abstract method withPage(int) in 
```

https://github.com/spring-projects/spring-boot/issues/25746

**Comment by mp911de** [comment]
`Pageable` was never intended to be implemented outside of Spring Data. 

Adding a default implementation would fall back to Spring Data's `PageRequest` and any custom implementation would get lost as the default would call `PageRequest.of(pageNumber, getPageSize(), getSort())`. Doing so would potentially introduce a bug that is hard to spot. The alternative, throwing `UnsupportedOperationException` isn't ideal either calls to this method would potentially go unnoticed since the new method isn't likely to exist in your test code.

We still have a few pre-releases where we can improve on that end if you have suggestions.

**Comment by khmarbaise** [comment]
From my point of view if an interface is not intended to be implemented (outside the framework) it might be a good idea to mark that somehow (maybe in the javadoc or maybe via API guardian or alike). The other thing is we are using Vaadin and have the issue to reload a larger amount of elements (and jumping via scrollbar etc.) and not strictly page oriented (Vaadin does that?) ... 

To be honest I don't know if any kind of default implementation etc. makes sense...

**Comment by mp911de** [comment]
Probably a good opportunity to replace their custom Pageable implementation with the one from Spring Data. Happy to learn what the use case is to ship an own implementation.

**Comment by mp911de** [comment]
Since there's nothing really actionable here, I'm closing this ticket.
