### ISSUE TITLE
Interface `Persistable` not `Serializable` anymore

### ISSUE THREAD

**Issue by pranayhira** [spring-projects/spring-data-commons#2443]
L.S.

I was updating Spring data jpa from 1.13.x to 2.5.x

At a certain point, we discovered that our id fields were missing after the object was saved/retrieved from Redis. 
We are using 'default' JdkSerializationRedisSerializer to serialize the objects to Redis. 

A bit deep diving we noticed that the Persistable interface was not extending Serializable anymore and it seems unintentionally https://github.com/spring-projects/spring-data-commons/commit/727ab8384cac21e574526f325e19d6af92b8c8df#diff-2ffea8def1a1e1da09e729655a1347baed969c777687eb4c4396852c27cd2b1b

Can you elaborate?

**Comment by mp911de** [comment]
The `Persistable` abstraction originated in JPA where Hibernate/JPA requires for some hard-to-follow reasons the identifiers to be serializable. 

With the rewrite to Spring Data 2.0, we decided to lift that requirement as the majority of store modules do not require `Serializable` in the first place. Actually, JDK serialization throws an exception when an object isn't serializable so I'm wondering why some values are silently missing.

In any case, the removal of `Serializable` is intentional.
