### ISSUE TITLE
CVEs with spring-data-commons

### ISSUE THREAD

**Issue by vivek-mcafee** [spring-projects/spring-data-commons#2731]
There are following CVEs with spring-data-commons 2.7.5 version.

1. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003
2. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908
3. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237

https://mvnrepository.com/artifact/org.springframework.data/spring-data-commons/2.7.5

**Comment by jxblum** [comment]
First off, Spring Data Commons (SDC) `main` / `3.0` [uses](https://github.com/spring-projects/spring-data-commons/blob/main/pom.xml#L26-L29) the Spring Data Build (SDB) project ([here](https://github.com/spring-projects/spring-data-build)) parent Maven POM ([here](https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml)) to manage dependencies.

Similar SD Commons `2.7.x` [builds on](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/pom.xml#L12-L16) SD Build `2.7.x` and SD Commons `2.6.x` [builds on](https://github.com/spring-projects/spring-data-commons/blob/2.6.x/pom.xml#L12-L16) SD Build `2.6.x`.

CVE-2022-42003 - Jackson

Regarding [CVE-2022-42003](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003), SD Commons (via SD Build) has already been [upgraded](https://github.com/spring-projects/spring-data-build/blob/main/parent/pom.xml#L108) to Jackson `2.14.0`, which fixes the issue (see [here](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14)).

SD Commons/Build `2.7.x` ([here](https://github.com/spring-projects/spring-data-build/blob/2.7.x/parent/pom.xml#L106)) and `2.6.x` ([here](https://github.com/spring-projects/spring-data-build/blob/2.6.x/parent/pom.xml#L105)) either are already or likely to upgrade to versions of Jackson that resolve the CVE before our next [scheduled](https://calendar.spring.io/) maintenance releases and final SD `3.0` GA.

CVE-2020-8908 - Google Guava

Regarding [CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908), while SD Commons does have an "optional" dependency ([here](https://github.com/spring-projects/spring-data-commons/blob/main/pom.xml#L168-L173), or in `2.7.x`, [here](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/pom.xml#L212-L217)) on Google Guava, SD Commons does NOT use the API (namely, `com.google.common.io.Files.createTempDir()`) in question at all. In fact, there is no temporary directory creation of any kind, with any API, Java or otherwise, in SD Commons.

> NOTE: This CVE is rather dated (2020), and if it had been an issue in SD Commons, we would addressed it already.

> NOTE: However, it is likely that we should consider upgrading to the latest Guava version, which appears to be `v31.0` on the [GitHub project site](https://github.com/google/guava).

CVE-2018-10237

Regarding [CVE-2018-10237](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10237), again SD Commons (`2.7.x`) does NOT use the API (namely, `AtomicDoubleArray`) is NOT used by SD Commons at all.

> NOTE: Again, this CVE is rather dated (2018), and we would have likely addressed this already if it had been an issue.

> NOTE: The only presence of Google Guava in Spring Data Commons at all is the ([optional](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/src/main/java/org/springframework/data/util/NullableWrapperConverters.java#L60-L61)) use of the `com.google.common.base.Optional` in the SD Commons' `NullableWrapperConverters` class (see [here](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/src/main/java/org/springframework/data/util/NullableWrapperConverters.java#L38)).

CONCLUSION:

Finally, I'd like to point out that both [Jackson](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/pom.xml#L55-L59) and [Google Guava](https://github.com/spring-projects/spring-data-commons/blob/2.7.x/pom.xml#L212-L217) dependencies are "**optional**" in Spring Data Commons.

Neither dependency is required for the proper functioning of SD Commons. It really depends on 1) your UC as well as 2) the underlying Spring Data module that you are using (e.g. Spring Data Redis).

Additionally, given they are "optional" dependencies, neither dependency should pulled in by SD Commons as transitive dependencies unless you explicitly do so yourself, in our Spring Data application Maven POM or Gradle build file.

**Comment by jxblum** [comment]
Waiting for additional feedback on this from @mp911de.

**Comment by jxblum** [comment]
Regarding Jackson on SD Commons/Build `2.7.x`, see: https://github.com/spring-projects/spring-data-build/pull/1861.

Regarding Jackson on SD Commons/Build `2.6.x`, see: https://github.com/spring-projects/spring-data-build/pull/1862.

**Comment by mp911de** [comment]
Fixed via https://github.com/spring-projects/spring-data-build/issues/1863
