### ISSUE TITLE
Introduce Kotlin CoroutineQuerydslPredicateExecutor

### ISSUE THREAD

**Issue by christophejan** [spring-projects/spring-data-commons#2783]
Could you please introduce in `spring-data-commons` a Kotlin `CoroutineQuerydslPredicateExecutor`

`ReactiveCrudRepository` has Kotlin `CoroutineCrudRepository`
`ReactiveSortingRepository` has Kotlin `CoroutineSortingRepository`

but `ReactiveQuerydslPredicateExecutor` don't seem to have a similar 'Coroutine' interface

**Comment by mp911de** [comment]
All of our Kotlin Coroutine support is based on our reactive infrastructure, effectively translating Coroutine API calls to reactive API and their results back into Coroutine results. There is no implementation of `QuerydslPredicateExecutor` and we will not introduce one because the adapter infrastructure would not work with such an approach.

Using adapters avoids the need to duplicate all of our code just to provide another API flavor, however the flipside is that we do not support customizations expressed as Kotlin Coroutine code, neither in fragments nor in the extensions we ship.
