### ISSUE TITLE
First page number is 0 in the API response when using spring data one-indexed-parameters

### ISSUE THREAD

**Issue by sundarsabapathi** [spring-projects/spring-data-commons#2811]
I am using `spring-boot-starter-web` and `spring-boot-starter-jpa` to developing a REST API.
I am trying to make an API page start from 1 instead of 0.

I configured the following property `spring.data.web.pageable.one-indexed-parameters=true` in `application.properties` file.

Here is my current endpoint implementation code:

    @GetMapping(value = "/alluser", produces = MediaType.APPLICATION_JSON_VALUE)
     public Page<User> getUserinfo(Pageable pageable) 
     {
          Page<User> userPage = userService.getAllUserInfo(pageable);
          List<User> userResultList = userPage.getContent();
          userResultList = userResultList.stream().map(userObj -> {
              converterService.convertToDto(userObj);
    	  return userObj;
          }).collect(Collectors.toList());
    
          Page<User> userDtoPage = new PageImpl<>(userResultList, pageable, userPage.getTotalElements());
          return userDtoPage;
     }
When the above REST endpoint is invoked as below

http://localhost:9091/user-management/userinfo/alluser

Then I get the following response 

    {
      "content": [
        {
          "userId": "111",
          "userName": "First Demo"
        },
        {
          "userId": "222",
          "userName": "Second Demo"
        }
      ],
      "pageable": {
        "sort": {
          "empty": true,
          "sorted": false,
          "unsorted": true
        },
        "offset": 0,
        "pageNumber": 0,
        "pageSize": 2,
        "paged": true,
        "unpaged": false
      },
      "last": false,
      "totalElements": 8,
      "totalPages": 4,
      "size": 2,
      "number": 0,
      "sort": {
        "empty": true,
        "sorted": false,
        "unsorted": true
      },
      "first": true,
      "numberOfElements": 2,
      "empty": false
    }

I am expecting the `pageNumber` to be 1, however it is 0.

**Comment by quaff** [comment]
@sundarsabapathi You should provide a minimal reproducer.

**Comment by sundarsabapathi** [comment]
Hi @quaff, Sorry for the late reply. I reproduce the issue with minimal code and attached the zip file. Please give your feedback.


[pagination-rest-api.zip](https://github.com/spring-projects/spring-data-commons/files/11862696/pagination-rest-api.zip)

**Comment by odrotbohm** [comment]
Serializing `Page` instances directly is not supported as it is a domain type. To render those properly considering the settings, you need to return a `PagedModel` available through Spring HATEOAS. You can declare a `PagedResourceAssembler` as handler method argument and call `….toModel(…)` on that to produce a properly serialized representation.

**Comment by sundarsabapathi** [comment]
Thanks @odrotbohm. I follow your suggestion to try again.

**Comment by lowcasz** [comment]
@odrotbohm
> Serializing `Page` instances directly is not supported as it is a domain type. To render those properly considering the settings, you need to return a `PagedModel` available through Spring HATEOAS. You can declare a `PagedResourceAssembler` as handler method argument and call `….toModel(…)` on that to produce a properly serialized representation.

Regardless of it being a domain object, it looks like an error. The Page should be constructed based on Pageable and contain its parameters, similar to the PageImpl instance, even if the parameter only concerns the way Pageable is built.
Regarding HATEOAS, it would be good if there were built-in support for fixing links because it's not easy for beginners to find information on how to fix this, especially given that the same parameter could be used in spring-data-rest.

**Comment by odrotbohm** [comment]
> Regardless of it being a domain object, it looks like an error.
`Page` looks like an error? I cannot follow.
> The Page should be constructed based on Pageable and contain its parameters, similar to the PageImpl instance, even if the parameter only concerns the way Pageable is built.
I am unable to follow here, either. The ticket is about *serializing* `Page` instances and in how far serialization to JSON is supported out of the box.
> Regarding HATEOAS, it would be good if there were built-in support for fixing links because it's not easy for beginners to find information on how to fix this, especially given that the same parameter could be used in spring-data-rest.
The reference documentation contains a [dedicated section](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#core.web.pageables) on the web aspects of serializing `Page`/`Slice`. Furthermore, Spring Data REST actually uses Spring HATEOAS under the covers and does exactly what I suggested above and is laid out in the documentation.

**Comment by lowcasz** [comment]
This seems more crazy than I thought. :/ I initially believed that the Pageable object would take the same value as in the URL, but now I see that it is modified during the binding of the address to PageRequest. This generates many problems because, from the HTTP layer, page parameter is other than page parameter in the query, but in the case of HATEOAS, the links to the beginning of the resources are incorrectly generated as they should contain page=1 instead of page=0.

This approach is very confusing, and I would consider starting a new issue to:

- either completely remove the existence of the misleading one-indexed-parameters parameter and let users take care of customizing the binding themselves
- or properly map both the request and response when changing the domain logic is too complicated

**Comment by odrotbohm** [comment]
As a first measure, let's stop derailing the original reporter's problem with completely unrelated aspects (the way you assume query parameters to look like and work, for example).
