### ISSUE TITLE
Converter<S, T> declared as lambdas aren't able to recognise generics

### ISSUE THREAD

**Issue by Fraser-Chapman** [spring-projects/spring-data-commons#2909]
# Description

This may be an issue for Oracle to look into as opposed to yourselves but raising here for awareness to start. FYI I'm compiling and running with Java 17.

When implementing the `Converter<S, T>` classes, if you create your anonymous class using the lambda shorthand, Spring is unable to resolve type arguments resulting in this error: `Couldn't resolve type arguments for class: path.to.my.CustomConversionBeans.class`.

**Shorthand:** `final Converter<Decimal128, BigDecimal> decimal128ToBigDecimal = decimal128 -> decimal128.bigDecimalValue();`

When declaring as an anonymous class or a concrete class, there is no issue.

# Demo Project

I have created an example project to demonstrate the issue:

https://github.com/Fraser-Chapman/generic-anonymous-class-as-lambda-issue

**Comment by mp911de** [comment]
This is expected behavior. Lambda classes do not retain generic type information when they are compiled into bytecode. Therefore, Spring cannot do anything here. 

To improve the usage experience of Lambda's, we introduced `ConverterBuilder`. You can use it as follows:

```java
ConverterBuilder.reading(String.class, Long.class, string -> …).andWriting(aLong -> )
```

You can use the resulting value (`ConverterAware`) with `CustomConversions`.

**Comment by Fraser-Chapman** [comment]
Ahh yes, you are correct. Thanks for educating me on that (\*facepalm*\)! Given it a go in my demo project and it's a super cool solution. Sorry for wasting your time.
