### ISSUE TITLE
`NullableWrapperToVavrOptionConverter` fails after vavr upgrade with Method `Option.none()` must be Methodref constant

### ISSUE THREAD

**Issue by AlbertSnows** [spring-projects/spring-data-commons#2946]
Problem: starter-data-r2dbc library throws exception when booting up a spring boot webflux project that also includes vavr

Java SDK: Eclipse Temurin version 20.0.2

Exception: 
```
2023-09-27T13:54:49.798-0500 [QUIET] [system.out] 2023-09-27T13:54:49.799-05:00  WARN 5271 --- [           main] onfigReactiveWebServerApplicationContex
t : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error cre
ating bean with name 'r2dbcEntityTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/r2dbc/R2dbcDataAutoConfiguration.
class]: Failed to instantiate [org.springframework.data.r2dbc.core.R2dbcEntityTemplate]: Factory method 'r2dbcEntityTemplate' threw exception with messa
ge: Method 'io.vavr.control.Option io.vavr.control.Option.none()' must be Methodref constant
```

Files: 
This problem can be recreated with a minimal project build off of the spring initializer, with some minor tweaks for the following files. 

`build.gradle`
```gradle

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.3'
    id 'io.spring.dependency-management' version '1.1.3'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc' // <-- commenting this line "resolves" the issue
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    runtimeOnly('io.r2dbc:r2dbc-h2:1.0.0.RELEASE')
    implementation 'io.vavr:vavr:1.0.0-alpha-4'
}
```

application.yml
```yaml
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb #create DB in memory
```

**Comment by mp911de** [comment]
The referenced version [vavr-1.0.0-alpha-4](https://github.com/vavr-io/vavr/releases/tag/vavr-1.0.0-alpha-4) was released a couple of years ago. Since then, no new release has been shipped. Vavr's future is highly unpredictable and the 1.x development line comes with several binary breaking changes, e.g. `Option` was migrated from an interface into an abstract class (that is the reason you see the exception).

Judging from [Daniel's comment](https://github.com/vavr-io/vavr/issues/2749#issuecomment-1642648511) the alpha version was a playground with a high chance of going back to the 0.10.x design.

At the moment, we do not intend to apply any changes as the future is uncertain and we will reconsider our vavr support for evolution once there is a stable path forward for vavr.

**Comment by AlbertSnows** [comment]
noted, thanks for sharing your thoughts.
