### ISSUE TITLE
`TypeDiscoverer` uses single-level nesting for generics comparison

### ISSUE THREAD

**Issue by jinganix** [spring-projects/spring-data-commons#3051]
DEMO repo: https://github.com/jinganix/spring-data-mongodb-issue

When running test in ConverterTest.java, it will throw error:

```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.math.BigDecimal] for value [Bar]
```

There is no error if we removed this line: https://github.com/jinganix/spring-data-mongodb-issue/blob/296bd2c3a801f54f35e794dec2a3af12229f6a54/src/test/java/com/example/demo/model/FooCollection.java#L13

please have a check

**Comment by mp911de** [comment]
The problem comes from `TypeDiscoverer` that resolves generics to a `Class` and then compares classes for equality. Reducing the type to `Class` erases the inner parameters (`MyContainer<List<String>>` vs `MyContainer<List<Map<…>>`) to `List.class` for both cases and therefore, the comparison falsely matches.
